/**
 * XLSX renderer for a workspace export — one summary sheet plus one sheet
 * per module, with frozen headers, autofilter and sized columns.
 */
import ExcelJS from "exceljs";
import { EMPTY_VALUE, type ExportBundle, type ExportSection } from "./export";

const ACCENT = "FF5B76FE";
const HEAD_BG = "FFEEF1FE";
const STRIPE = "FFF7F8FB";
const BORDER = "FFE2E4EA";
const INK = "FF12131A";
const FAINT = "FF9AA0AE";

// Excel forbids : \ / ? * [ ] in sheet names and caps them at 31 chars.
function sheetName(label: string, used: Set<string>): string {
  const base = label.replace(/[:\\/?*[\]]/g, "-").slice(0, 31) || "Sheet";
  let name = base;
  let n = 2;
  while (used.has(name.toLowerCase())) {
    const suffix = ` (${n++})`;
    name = base.slice(0, 31 - suffix.length) + suffix;
  }
  used.add(name.toLowerCase());
  return name;
}

function styleHeader(row: ExcelJS.Row, count: number) {
  row.height = 22;
  for (let i = 1; i <= count; i++) {
    const cell = row.getCell(i);
    cell.font = { bold: true, size: 10, color: { argb: ACCENT } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEAD_BG } };
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = { bottom: { style: "thin", color: { argb: ACCENT } } };
  }
}

function addSheet(wb: ExcelJS.Workbook, section: ExportSection, used: Set<string>) {
  const ws = wb.addWorksheet(sheetName(section.label, used), {
    views: [{ state: "frozen", ySplit: 1 }],
    properties: { defaultRowHeight: 16 },
  });

  ws.columns = section.columns.map((c) => ({
    header: c.label,
    key: c.key,
    width: c.long ? 52 : c.key === "id" ? 8 : c.key === section.titleKey ? 38 : 18,
  }));
  styleHeader(ws.getRow(1), section.columns.length);

  section.rows.forEach((row, ri) => {
    const added = ws.addRow(section.columns.map((c) => row[c.key] ?? EMPTY_VALUE));
    added.alignment = { vertical: "top", wrapText: true };
    section.columns.forEach((c, ci) => {
      const cell = added.getCell(ci + 1);
      const empty = cell.value === EMPTY_VALUE;
      cell.font = {
        size: 10,
        color: { argb: empty ? FAINT : INK },
        italic: empty,
        bold: !empty && c.key === section.titleKey,
      };
      cell.border = { bottom: { style: "hair", color: { argb: BORDER } } };
      if (ri % 2 === 1 && !empty) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE } };
      }
    });
  });

  if (section.rows.length > 0) {
    ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: section.columns.length } };
  } else {
    const empty = ws.addRow([EMPTY_VALUE]);
    empty.getCell(1).font = { italic: true, size: 10, color: { argb: FAINT } };
  }
}

function addSummary(wb: ExcelJS.Workbook, bundle: ExportBundle) {
  const ws = wb.addWorksheet("Summary", { views: [{ state: "frozen", ySplit: 6 }] });
  ws.columns = [{ width: 32 }, { width: 46 }];

  const title = ws.addRow([`${bundle.project.name} — Workspace Export`]);
  title.font = { bold: true, size: 15, color: { argb: INK } };
  title.height = 26;

  const sub = ws.addRow([bundle.project.key]);
  sub.font = { size: 10, color: { argb: FAINT } };
  ws.addRow([]);

  const meta: [string, string][] = [
    ["Generated", bundle.generatedAt.toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })],
    ["Generated by", bundle.generatedBy],
    ["Total records", String(bundle.totalRecords)],
  ];
  for (const [k, v] of meta) {
    const r = ws.addRow([k, v]);
    r.getCell(1).font = { size: 10, color: { argb: FAINT } };
    r.getCell(2).font = { size: 10, bold: true, color: { argb: INK } };
  }
  ws.addRow([]);

  const head = ws.addRow(["Module", "Records"]);
  styleHeader(head, 2);
  for (const s of bundle.sections) {
    const r = ws.addRow([s.label, s.rows.length || EMPTY_VALUE]);
    r.getCell(1).font = { size: 10, color: { argb: INK } };
    r.getCell(2).font = {
      size: 10,
      bold: s.rows.length > 0,
      italic: s.rows.length === 0,
      color: { argb: s.rows.length ? ACCENT : FAINT },
    };
    r.eachCell((c) => { c.border = { bottom: { style: "hair", color: { argb: BORDER } } }; });
  }
}

export async function renderXlsx(bundle: ExportBundle): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "BugBase";
  wb.created = bundle.generatedAt;

  addSummary(wb, bundle);
  const used = new Set<string>(["summary"]);
  for (const section of bundle.sections) addSheet(wb, section, used);

  return Buffer.from(await wb.xlsx.writeBuffer());
}
